project_id = "gxllyxusfyjjqpqylxrs"

[functions.mapbox-token]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true

[functions.process-pdf]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = false
