project_id = "gxllyxusfyjjqpqylxrs"

[functions.mapbox-token]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.process-pdf]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = true
